name: coverage workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test project
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
